import { useState, useEffect, useMemo } from 'react'
import { db } from '../../firebase'
import { collection, query, where, getDocs } from 'firebase/firestore'

function ViewSGPA() {
  // Dropdown options
  const [academicYears, setAcademicYears] = useState([])
  const [semesters, setSemesters] = useState([])
  const [batches, setBatches] = useState([])

  // Selected filters
  const [selectedYear, setSelectedYear] = useState('')
  const [selectedSem, setSelectedSem] = useState('')
  const [selectedBatch, setSelectedBatch] = useState('')

  const [results, setResults] = useState([])
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(false)
  const [alert, setAlert] = useState(null)
  const [hasSearched, setHasSearched] = useState(false)

  // Populate filter options from `sgpaResults`
  useEffect(() => {
    async function loadArchivedOptions() {
      try {
        const snapshot = await getDocs(collection(db, 'sgpaResults'))
        const ySet = new Set()
        const sSet = new Set()
        const bSet = new Set()

        snapshot.forEach(d => {
          const data = d.data()
          if (data.academicYear) ySet.add(data.academicYear)
          if (data.semester) sSet.add(data.semester)
          if (data.batch) bSet.add(data.batch)
        })

        setAcademicYears([...ySet])
        setSemesters([...sSet])
        setBatches([...bSet])
      } catch (err) {
        console.error('Error loading archived options:', err)
      }
    }

    loadArchivedOptions()
  }, [])

  // Load Saved SGPA
  const handleLoadSavedSGPA = async () => {
    setAlert(null)

    if (!selectedYear || !selectedSem || !selectedBatch) {
      setAlert({ type: 'error', message: '⚠️ Please select Academic Year, Semester, and Batch.' })
      return
    }

    try {
      setLoading(true)
      setHasSearched(true)
      const q = query(
        collection(db, 'sgpaResults'),
        where('batch', '==', selectedBatch),
        where('semester', '==', selectedSem),
        where('academicYear', '==', selectedYear)
      )

      const snapshot = await getDocs(q)
      const list = []
      snapshot.forEach(d => {
        list.push({ id: d.id, ...d.data() })
      })

      list.sort((a, b) => parseFloat(b.sgpa) - parseFloat(a.sgpa))
      setResults(list)

      if (list.length === 0) {
        setAlert({ type: 'error', message: '📭 No archived SGPA records found for the selected batch.' })
      } else {
        setAlert({ type: 'success', message: `✅ Loaded ${list.length} archived semester records.` })
      }
    } catch (err) {
      console.error('Error loading archived SGPA:', err)
      setAlert({ type: 'error', message: `⚠️ ${err.message}` })
    } finally {
      setLoading(false)
    }
  }

  // Live search filtering
  const filteredResults = useMemo(() => {
    const sTerm = search.toLowerCase().trim()
    if (!sTerm) return results
    return results.filter(r =>
      (r.name && r.name.toLowerCase().includes(sTerm)) ||
      (r.rollNo && r.rollNo.toLowerCase().includes(sTerm))
    )
  }, [results, search])

  // Aggregate stats
  const stats = useMemo(() => {
    if (results.length === 0) return { count: 0, avg: '0.00', high: '0.00', low: '0.00' }
    const sgpas = results.map(r => Number(r.sgpa) || 0)
    const avg = (sgpas.reduce((a, b) => a + b, 0) / sgpas.length).toFixed(2)
    const high = Math.max(...sgpas).toFixed(2)
    const low = Math.min(...sgpas).toFixed(2)
    return { count: results.length, avg, high, low }
  }, [results])

  // Export CSV
  const handleExportCSV = () => {
    if (filteredResults.length === 0) return

    const headers = ['Roll No', 'Student Name', 'Batch', 'Semester', 'Academic Year', 'SGPA', 'Total Credits', 'Generated On', 'Generated By']
    const rows = filteredResults.map(r => [
      r.rollNo, r.name, r.batch, r.semester, r.academicYear, r.sgpa, r.totalCredits, r.generatedOn, r.generatedBy || ''
    ])

    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${String(cell ?? '').replace(/"/g, '""')}"`).join(','))
      .join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `UniGrade_SGPA_Results_${selectedBatch}_${selectedSem}.csv`
    link.click()
    URL.revokeObjectURL(url)
  }

  return (
    <main className="dashboard-container">
      {/* Header */}
      <div className="dashboard-top fade-up">
        <span className="page-badge">INSTITUTION PORTAL</span>
        <h1 className="dashboard-title">Archived SGPA Results</h1>
        <p className="dashboard-subtitle">
          View previously generated semester results and performance analytics across batches and academic years.
        </p>
      </div>

      {/* Alert */}
      {alert && (
        <div className={`alert alert-${alert.type}`}>
          {alert.message}
        </div>
      )}

      {/* Filter Card */}
      <div className="card fade-up">
        <h3 style={{ color: 'var(--primary)', fontSize: 18, fontWeight: 700, margin: '0 0 18px' }}>
          Filter Archived Results
        </h3>

        <div className="grid-4">
          <div>
            <label htmlFor="archYear">Academic Year *</label>
            <select
              id="archYear"
              value={selectedYear}
              onChange={(e) => setSelectedYear(e.target.value)}
            >
              <option value="">Select Academic Year</option>
              {academicYears.map((y, i) => (
                <option key={i} value={y}>{y}</option>
              ))}
            </select>
          </div>

          <div>
            <label htmlFor="archSem">Semester *</label>
            <select
              id="archSem"
              value={selectedSem}
              onChange={(e) => setSelectedSem(e.target.value)}
            >
              <option value="">Select Semester</option>
              {semesters.map((s, i) => (
                <option key={i} value={s}>{s}</option>
              ))}
            </select>
          </div>

          <div>
            <label htmlFor="archBatch">Batch *</label>
            <select
              id="archBatch"
              value={selectedBatch}
              onChange={(e) => setSelectedBatch(e.target.value)}
            >
              <option value="">Select Batch</option>
              {batches.map((b, i) => (
                <option key={i} value={b}>{b}</option>
              ))}
            </select>
          </div>

          <div style={{ display: 'flex', alignItems: 'flex-end' }}>
            <button
              type="button"
              onClick={handleLoadSavedSGPA}
              className="btn-primary"
              disabled={loading}
              style={{ width: '100%', padding: '11px 20px', height: 42 }}
            >
              {loading ? 'Loading...' : 'View Results →'}
            </button>
          </div>
        </div>
      </div>

      {/* Results Content */}
      {hasSearched && results.length > 0 && (
        <div className="fade-up">
          {/* Summary Stats */}
          <div className="stats-grid" style={{ marginBottom: 28 }}>
            <div className="stat-card">
              <h2>{stats.count}</h2>
              <p>Total Students</p>
            </div>
            <div className="stat-card">
              <h2>{stats.avg}</h2>
              <p>Average SGPA</p>
            </div>
            <div className="stat-card">
              <h2 style={{ color: '#059669' }}>{stats.high}</h2>
              <p>Highest SGPA</p>
            </div>
            <div className="stat-card">
              <h2 style={{ color: '#dc2626' }}>{stats.low}</h2>
              <p>Lowest SGPA</p>
            </div>
          </div>

          {/* Search & Results Table */}
          <div className="card" style={{ padding: 20 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16, flexWrap: 'wrap', gap: 10 }}>
              <h3 style={{ color: 'var(--primary)', fontSize: 17, fontWeight: 700, margin: 0 }}>
                Semester Results ({filteredResults.length})
              </h3>

              <button
                type="button"
                onClick={handleExportCSV}
                className="btn-primary"
                style={{ width: 'auto', padding: '10px 20px', fontSize: 13.5 }}
              >
                📤 Export CSV
              </button>
            </div>

            <div style={{ marginBottom: 16 }}>
              <input
                type="text"
                placeholder="🔍 Search by Roll No or Student Name..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                style={{ margin: 0 }}
              />
            </div>

            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Rank</th>
                    <th>Roll No</th>
                    <th>Student Name</th>
                    <th>SGPA</th>
                    <th>Total Credits</th>
                    <th>Generated On</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredResults.map((s, i) => (
                    <tr key={s.id}>
                      <td><strong>#{i + 1}</strong></td>
                      <td>{s.rollNo}</td>
                      <td><strong>{s.name}</strong></td>
                      <td><strong style={{ color: 'var(--primary)', fontSize: 15 }}>{s.sgpa}</strong></td>
                      <td>{s.totalCredits}</td>
                      <td style={{ fontSize: 12.5, color: 'var(--text-muted)' }}>{s.generatedOn}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Empty State before search */}
      {!hasSearched && (
        <div className="empty-state fade-up">
          <div className="empty-icon">📂</div>
          <h3>No Results Loaded</h3>
          <p>Select Academic Year, Semester, and Batch above to view archived SGPA results.</p>
        </div>
      )}
    </main>
  )
}

export default ViewSGPA
